{% set name = "dirtyjson" %}
{% set version = "1.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dirtyjson-{{ version }}.tar.gz
  sha256: 90ca4a18f3ff30ce849d100dcf4a003953c79d3a2348ef056f1d9c22231a25fd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - dirtyjson
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/codecobblers/dirtyjson
  summary: JSON decoder for Python that can extract data from the muck
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - pavelzw
